<?php

/**
 * @file
 * Manages the cohesive administration section for Springboard.
 */


/**
 * Implements hook_admin_paths().
 */
function springboard_admin_paths() {
  return array(
    'springboard' => TRUE,
    'springboard/*' => TRUE,
  );
}

/**
 * Implements hook_menu().
 */
function springboard_admin_menu() {
  $items = array();

  // List all springboard config pages.
  $items['springboard'] = array(
    'title' => 'Administer Springboard',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_modules_page',
    'file path' => drupal_get_path('module', 'springboard'),
    'file' => 'springboard.admin.inc',
  );

  // Primary administration pages.
  $items['springboard/dashboard'] = array(
    'title' => 'Springboard',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_dashboard_page',
    'weight' => -20,
    'file' => 'includes/wireframes.admin.inc',
    'menu_name' => 'springboard-admin',
  );
  $items['springboard/donation-forms'] = array(
    'title' => 'Donation Forms',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_block_page',
    'page arguments' => array('donation-forms'),
    'weight' => -16,
    'file' => 'includes/admin.inc',
    'menu_name' => 'springboard-admin',
  );
  $items['springboard/forms'] = array(
    'title' => 'Forms',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_block_page',
    'page arguments' => array('forms'),
    'weight' => -12,
    'file' => 'includes/admin.inc',
    'menu_name' => 'springboard-admin',
  );
  $items['springboard/templates'] = array(
    'title' => 'Templates',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_templates_page',
    'weight' => -8,
    'file' => 'includes/wireframes.admin.inc',
    'menu_name' => 'springboard-admin',
  );
  $items['springboard/analytics'] = array(
    'title' => 'Marketing & Analytics',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_analytics_page',
    'weight' => -4,
    'file' => 'includes/wireframes.admin.inc',
    'menu_name' => 'springboard-admin',
  );
  $items['springboard/reports'] = array(
    'title' => 'Results',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_block_page',
    'page arguments' => array('reports'),
    'weight' => -1,
    'file' => 'includes/admin.inc',
    'menu_name' => 'springboard-admin',
  );
  $items['springboard/config'] = array(
    'title' => 'Settings',
    'access arguments' => array('administer springboard'),
    'page callback' => 'springboard_admin_block_page',
    'page arguments' => array('config'),
    'weight' => 20,
    'file' => 'includes/admin.inc',
    'menu_name' => 'springboard-admin',
  );

  return $items;
}

/**
 * Implements hook_page_build().
 */
function springboard_admin_page_build(&$page) {
  if (arg(0) == 'springboard') {
    module_load_include('inc', 'springboard_admin', 'includes/wireframes.admin');
    _springboard_admin_add_wireframes_to_page($page);
  }
}
